# Generated by Django 4.1 on 2022-08-26 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppIntermedia', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Secretario',
            new_name='Supervisor',
        ),
    ]
